//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://IcelandicOnlineBanking/2012/04/13/DocumentTypes")]
    [System.SerializableAttribute()]
    public partial class Document : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentInfo DocumentInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentInfo DocumentInfo {
            get {
                return this.DocumentInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentInfoField, value) != true)) {
                    this.DocumentInfoField = value;
                    this.RaisePropertyChanged("DocumentInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] File {
            get {
                return this.FileField;
            }
            set {
                if ((object.ReferenceEquals(this.FileField, value) != true)) {
                    this.FileField = value;
                    this.RaisePropertyChanged("File");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentInfo", Namespace="http://IcelandicOnlineBanking/2012/04/13/DocumentTypes")]
    [System.SerializableAttribute()]
    public partial class DocumentInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonIDField, value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DocumentType {
            get {
                return this.DocumentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentTypeField, value) != true)) {
                    this.DocumentTypeField = value;
                    this.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DocumentName {
            get {
                return this.DocumentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNameField, value) != true)) {
                    this.DocumentNameField = value;
                    this.RaisePropertyChanged("DocumentName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IOBSFault", Namespace="http://IcelandicOnlineBanking/2012/11/01/Exceptions")]
    [System.SerializableAttribute()]
    public partial class IOBSFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneralErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneralErrorTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BanksErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BanksErrorTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneralSourceTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneralSourceCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GeneralErrorCode {
            get {
                return this.GeneralErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneralErrorCodeField, value) != true)) {
                    this.GeneralErrorCodeField = value;
                    this.RaisePropertyChanged("GeneralErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GeneralErrorText {
            get {
                return this.GeneralErrorTextField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneralErrorTextField, value) != true)) {
                    this.GeneralErrorTextField = value;
                    this.RaisePropertyChanged("GeneralErrorText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BanksErrorCode {
            get {
                return this.BanksErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BanksErrorCodeField, value) != true)) {
                    this.BanksErrorCodeField = value;
                    this.RaisePropertyChanged("BanksErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BanksErrorText {
            get {
                return this.BanksErrorTextField;
            }
            set {
                if ((object.ReferenceEquals(this.BanksErrorTextField, value) != true)) {
                    this.BanksErrorTextField = value;
                    this.RaisePropertyChanged("BanksErrorText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string GeneralSourceText {
            get {
                return this.GeneralSourceTextField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneralSourceTextField, value) != true)) {
                    this.GeneralSourceTextField = value;
                    this.RaisePropertyChanged("GeneralSourceText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string GeneralSourceCode {
            get {
                return this.GeneralSourceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneralSourceCodeField, value) != true)) {
                    this.GeneralSourceCodeField = value;
                    this.RaisePropertyChanged("GeneralSourceCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentResultQuery", Namespace="http://IcelandicOnlineBanking/2012/04/13/DocumentTypes")]
    [System.SerializableAttribute()]
    public partial class DocumentResultQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DocumentID {
            get {
                return this.DocumentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentIDField, value) != true)) {
                    this.DocumentIDField = value;
                    this.RaisePropertyChanged("DocumentID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentResult", Namespace="http://IcelandicOnlineBanking/2012/04/13/DocumentTypes")]
    [System.SerializableAttribute()]
    public partial class DocumentResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentInfo DocumentInfoField;
        
        private IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentProcessingStatus ProcessingStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentProcessingResult ProcessingResultField;
        
        private System.DateTime DateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DocumentID {
            get {
                return this.DocumentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentIDField, value) != true)) {
                    this.DocumentIDField = value;
                    this.RaisePropertyChanged("DocumentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentInfo DocumentInfo {
            get {
                return this.DocumentInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentInfoField, value) != true)) {
                    this.DocumentInfoField = value;
                    this.RaisePropertyChanged("DocumentInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentProcessingStatus ProcessingStatus {
            get {
                return this.ProcessingStatusField;
            }
            set {
                if ((this.ProcessingStatusField.Equals(value) != true)) {
                    this.ProcessingStatusField = value;
                    this.RaisePropertyChanged("ProcessingStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentProcessingResult ProcessingResult {
            get {
                return this.ProcessingResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessingResultField, value) != true)) {
                    this.ProcessingResultField = value;
                    this.RaisePropertyChanged("ProcessingResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentProcessingResult", Namespace="http://IcelandicOnlineBanking/2012/04/13/DocumentTypes")]
    [System.SerializableAttribute()]
    public partial class DocumentProcessingResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long RecordsProcessedField;
        
        private long RecordsSkippedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long RecordsProcessed {
            get {
                return this.RecordsProcessedField;
            }
            set {
                if ((this.RecordsProcessedField.Equals(value) != true)) {
                    this.RecordsProcessedField = value;
                    this.RaisePropertyChanged("RecordsProcessed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long RecordsSkipped {
            get {
                return this.RecordsSkippedField;
            }
            set {
                if ((this.RecordsSkippedField.Equals(value) != true)) {
                    this.RecordsSkippedField = value;
                    this.RaisePropertyChanged("RecordsSkipped");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentProcessingStatus", Namespace="http://IcelandicOnlineBanking/2012/04/13/DocumentTypes")]
    public enum DocumentProcessingStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Received ")]
        Received = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute(Value="InProgress ")]
        InProgress = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Completed ")]
        Completed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompletedWithErrors = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentsResultQuery", Namespace="http://IcelandicOnlineBanking/2012/04/13/DocumentTypes")]
    [System.SerializableAttribute()]
    public partial class DocumentsResultQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DateFromField;
        
        private string DateToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string DateFrom {
            get {
                return this.DateFromField;
            }
            set {
                if ((object.ReferenceEquals(this.DateFromField, value) != true)) {
                    this.DateFromField = value;
                    this.RaisePropertyChanged("DateFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string DateTo {
            get {
                return this.DateToField;
            }
            set {
                if ((object.ReferenceEquals(this.DateToField, value) != true)) {
                    this.DateToField = value;
                    this.RaisePropertyChanged("DateTo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://IcelandicOnlineBanking/2012/04/13/Documents", ConfigurationName="DocumentServiceProxy.IIcelandicOnlineBankingDocumentService")]
    public interface IIcelandicOnlineBankingDocumentService {
        
        // CODEGEN: Generating message contract since element name Document from namespace http://IcelandicOnlineBanking/2012/04/13/Documents is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://IcelandicOnlineBanking/2012/04/13/UploadDocument", ReplyAction="http://IcelandicOnlineBanking/2012/04/13/Documents/IIcelandicOnlineBankingDocumen" +
            "tService/UploadDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.IOBSFault), Action="http://IcelandicOnlineBanking/2012/04/13/UploadDocument", Name="IOBSFault", Namespace="http://IcelandicOnlineBanking/2012/11/01/Exceptions")]
        IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.UploadDocumentResponse UploadDocument(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.UploadDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name Query from namespace http://IcelandicOnlineBanking/2012/04/13/Documents is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://IcelandicOnlineBanking/2012/04/13/GetDocumentResult", ReplyAction="http://IcelandicOnlineBanking/2012/04/13/Documents/IIcelandicOnlineBankingDocumen" +
            "tService/GetDocumentResultResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.IOBSFault), Action="http://IcelandicOnlineBanking/2012/04/13/GetDocumentResult", Name="IOBSFault", Namespace="http://IcelandicOnlineBanking/2012/11/01/Exceptions")]
        IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentResultResponse GetDocumentResult(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentResultRequest request);
        
        // CODEGEN: Generating message contract since element name Query from namespace http://IcelandicOnlineBanking/2012/04/13/Documents is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://IcelandicOnlineBanking/2012/04/13/GetDocumentsResult", ReplyAction="http://IcelandicOnlineBanking/2012/04/13/Documents/IIcelandicOnlineBankingDocumen" +
            "tService/GetDocumentsResultResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.IOBSFault), Action="http://IcelandicOnlineBanking/2012/04/13/GetDocumentsResult", Name="IOBSFault", Namespace="http://IcelandicOnlineBanking/2012/11/01/Exceptions")]
        IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentsResultResponse GetDocumentsResult(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentsResultRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadDocument", Namespace="http://IcelandicOnlineBanking/2012/04/13/Documents", Order=0)]
        public IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.UploadDocumentRequestBody Body;
        
        public UploadDocumentRequest() {
        }
        
        public UploadDocumentRequest(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.UploadDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://IcelandicOnlineBanking/2012/04/13/Documents")]
    public partial class UploadDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.Document Document;
        
        public UploadDocumentRequestBody() {
        }
        
        public UploadDocumentRequestBody(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.Document Document) {
            this.Document = Document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadDocumentResponse", Namespace="http://IcelandicOnlineBanking/2012/04/13/Documents", Order=0)]
        public IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.UploadDocumentResponseBody Body;
        
        public UploadDocumentResponse() {
        }
        
        public UploadDocumentResponse(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.UploadDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://IcelandicOnlineBanking/2012/04/13/Documents")]
    public partial class UploadDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DocumentID;
        
        public UploadDocumentResponseBody() {
        }
        
        public UploadDocumentResponseBody(string DocumentID) {
            this.DocumentID = DocumentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentResult", Namespace="http://IcelandicOnlineBanking/2012/04/13/Documents", Order=0)]
        public IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentResultRequestBody Body;
        
        public GetDocumentResultRequest() {
        }
        
        public GetDocumentResultRequest(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://IcelandicOnlineBanking/2012/04/13/Documents")]
    public partial class GetDocumentResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentResultQuery Query;
        
        public GetDocumentResultRequestBody() {
        }
        
        public GetDocumentResultRequestBody(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentResultQuery Query) {
            this.Query = Query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentResultResponse", Namespace="http://IcelandicOnlineBanking/2012/04/13/Documents", Order=0)]
        public IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentResultResponseBody Body;
        
        public GetDocumentResultResponse() {
        }
        
        public GetDocumentResultResponse(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://IcelandicOnlineBanking/2012/04/13/Documents")]
    public partial class GetDocumentResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentResult DocumentResult;
        
        public GetDocumentResultResponseBody() {
        }
        
        public GetDocumentResultResponseBody(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentResult DocumentResult) {
            this.DocumentResult = DocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentsResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentsResult", Namespace="http://IcelandicOnlineBanking/2012/04/13/Documents", Order=0)]
        public IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentsResultRequestBody Body;
        
        public GetDocumentsResultRequest() {
        }
        
        public GetDocumentsResultRequest(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentsResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://IcelandicOnlineBanking/2012/04/13/Documents")]
    public partial class GetDocumentsResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentsResultQuery Query;
        
        public GetDocumentsResultRequestBody() {
        }
        
        public GetDocumentsResultRequestBody(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentsResultQuery Query) {
            this.Query = Query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentsResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentsResultResponse", Namespace="http://IcelandicOnlineBanking/2012/04/13/Documents", Order=0)]
        public IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentsResultResponseBody Body;
        
        public GetDocumentsResultResponse() {
        }
        
        public GetDocumentsResultResponse(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentsResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://IcelandicOnlineBanking/2012/04/13/Documents")]
    public partial class GetDocumentsResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.Collection<IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentResult> DocumentResults;
        
        public GetDocumentsResultResponseBody() {
        }
        
        public GetDocumentsResultResponseBody(System.Collections.ObjectModel.Collection<IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentResult> DocumentResults) {
            this.DocumentResults = DocumentResults;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIcelandicOnlineBankingDocumentServiceChannel : IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.IIcelandicOnlineBankingDocumentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IcelandicOnlineBankingDocumentServiceClient : System.ServiceModel.ClientBase<IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.IIcelandicOnlineBankingDocumentService>, IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.IIcelandicOnlineBankingDocumentService {
        
        public IcelandicOnlineBankingDocumentServiceClient() {
        }
        
        public IcelandicOnlineBankingDocumentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IcelandicOnlineBankingDocumentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IcelandicOnlineBankingDocumentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IcelandicOnlineBankingDocumentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.UploadDocumentResponse IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.IIcelandicOnlineBankingDocumentService.UploadDocument(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.UploadDocumentRequest request) {
            return base.Channel.UploadDocument(request);
        }
        
        public string UploadDocument(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.Document Document) {
            IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.UploadDocumentRequest inValue = new IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.UploadDocumentRequest();
            inValue.Body = new IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.UploadDocumentRequestBody();
            inValue.Body.Document = Document;
            IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.UploadDocumentResponse retVal = ((IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.IIcelandicOnlineBankingDocumentService)(this)).UploadDocument(inValue);
            return retVal.Body.DocumentID;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentResultResponse IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.IIcelandicOnlineBankingDocumentService.GetDocumentResult(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentResultRequest request) {
            return base.Channel.GetDocumentResult(request);
        }
        
        public IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentResult GetDocumentResult(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentResultQuery Query) {
            IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentResultRequest inValue = new IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentResultRequest();
            inValue.Body = new IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentResultRequestBody();
            inValue.Body.Query = Query;
            IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentResultResponse retVal = ((IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.IIcelandicOnlineBankingDocumentService)(this)).GetDocumentResult(inValue);
            return retVal.Body.DocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentsResultResponse IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.IIcelandicOnlineBankingDocumentService.GetDocumentsResult(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentsResultRequest request) {
            return base.Channel.GetDocumentsResult(request);
        }
        
        public System.Collections.ObjectModel.Collection<IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentResult> GetDocumentsResult(IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.DocumentsResultQuery Query) {
            IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentsResultRequest inValue = new IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentsResultRequest();
            inValue.Body = new IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentsResultRequestBody();
            inValue.Body.Query = Query;
            IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.GetDocumentsResultResponse retVal = ((IsIT.B2B.DocumentsServiceTest.DocumentServiceProxy.IIcelandicOnlineBankingDocumentService)(this)).GetDocumentsResult(inValue);
            return retVal.Body.DocumentResults;
        }
    }
}
