//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCard", Namespace="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardTypes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.CreditCardDetails))]
    public partial class CreditCard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardHolderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardOwnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CardIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardOwnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardHolderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AmountDueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LastYearTurnoverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardBrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CurrentYearTurnoverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.Amount DomesticUsageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.Amount ForeignUsageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AvailableBalanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardHolderName {
            get {
                return this.CardHolderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardHolderNameField, value) != true)) {
                    this.CardHolderNameField = value;
                    this.RaisePropertyChanged("CardHolderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardOwnerName {
            get {
                return this.CardOwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardOwnerNameField, value) != true)) {
                    this.CardOwnerNameField = value;
                    this.RaisePropertyChanged("CardOwnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long CardId {
            get {
                return this.CardIdField;
            }
            set {
                if ((this.CardIdField.Equals(value) != true)) {
                    this.CardIdField = value;
                    this.RaisePropertyChanged("CardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string CardOwnerId {
            get {
                return this.CardOwnerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CardOwnerIdField, value) != true)) {
                    this.CardOwnerIdField = value;
                    this.RaisePropertyChanged("CardOwnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string CardHolderId {
            get {
                return this.CardHolderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CardHolderIdField, value) != true)) {
                    this.CardHolderIdField = value;
                    this.RaisePropertyChanged("CardHolderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<decimal> AmountDue {
            get {
                return this.AmountDueField;
            }
            set {
                if ((this.AmountDueField.Equals(value) != true)) {
                    this.AmountDueField = value;
                    this.RaisePropertyChanged("AmountDue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<decimal> Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<decimal> LastYearTurnover {
            get {
                return this.LastYearTurnoverField;
            }
            set {
                if ((this.LastYearTurnoverField.Equals(value) != true)) {
                    this.LastYearTurnoverField = value;
                    this.RaisePropertyChanged("LastYearTurnover");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string CardType {
            get {
                return this.CardTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardTypeField, value) != true)) {
                    this.CardTypeField = value;
                    this.RaisePropertyChanged("CardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string CardBrand {
            get {
                return this.CardBrandField;
            }
            set {
                if ((object.ReferenceEquals(this.CardBrandField, value) != true)) {
                    this.CardBrandField = value;
                    this.RaisePropertyChanged("CardBrand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string CardRole {
            get {
                return this.CardRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.CardRoleField, value) != true)) {
                    this.CardRoleField = value;
                    this.RaisePropertyChanged("CardRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string BankNumber {
            get {
                return this.BankNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNumberField, value) != true)) {
                    this.BankNumberField = value;
                    this.RaisePropertyChanged("BankNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.DateTime IssueDate {
            get {
                return this.IssueDateField;
            }
            set {
                if ((this.IssueDateField.Equals(value) != true)) {
                    this.IssueDateField = value;
                    this.RaisePropertyChanged("IssueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public System.DateTime ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((this.ExpiryDateField.Equals(value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public System.Nullable<decimal> Limit {
            get {
                return this.LimitField;
            }
            set {
                if ((this.LimitField.Equals(value) != true)) {
                    this.LimitField = value;
                    this.RaisePropertyChanged("Limit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public System.Nullable<decimal> CurrentYearTurnover {
            get {
                return this.CurrentYearTurnoverField;
            }
            set {
                if ((this.CurrentYearTurnoverField.Equals(value) != true)) {
                    this.CurrentYearTurnoverField = value;
                    this.RaisePropertyChanged("CurrentYearTurnover");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.Amount DomesticUsage {
            get {
                return this.DomesticUsageField;
            }
            set {
                if ((object.ReferenceEquals(this.DomesticUsageField, value) != true)) {
                    this.DomesticUsageField = value;
                    this.RaisePropertyChanged("DomesticUsage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.Amount ForeignUsage {
            get {
                return this.ForeignUsageField;
            }
            set {
                if ((object.ReferenceEquals(this.ForeignUsageField, value) != true)) {
                    this.ForeignUsageField = value;
                    this.RaisePropertyChanged("ForeignUsage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public System.Nullable<decimal> AvailableBalance {
            get {
                return this.AvailableBalanceField;
            }
            set {
                if ((this.AvailableBalanceField.Equals(value) != true)) {
                    this.AvailableBalanceField = value;
                    this.RaisePropertyChanged("AvailableBalance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Amount", Namespace="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardTypes")]
    [System.SerializableAttribute()]
    public partial class Amount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCardDetails", Namespace="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardTypes")]
    [System.SerializableAttribute()]
    public partial class CreditCardDetails : IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.CreditCard {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CreditLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssuerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChargeBranchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChargeLedgerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChargeAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MinPaymentAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AuthorizationLimitValidToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AugmentedAuthorizationLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AugmentedAuthorizationLimitExpirationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.Amount ForeignAuthorizationLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.Amount AugmentedDomesticAuthorizationLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AugmentedDomesticAuthorizationLimitExpirationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.Amount AugmentedForeignAuthorizationLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AugmentedForeignAuthorizationLimitExpirationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IcelandairLoyaltyClubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PaymentMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PaymentDueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastPaymentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeclineBillingStatementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InCollectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> OlderDebtAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PenaltyInterestBaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LastDueAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BillingStatementInDefaultNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DuePenaltyInterestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PenaltyInterestCurrentPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TransactionAmountCurrentPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CardInstallmentLoanRemainingBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CardPaymentDistributionLoanRemainingBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LightCardInstallmentLoanRemainingBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrepaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PrePaidBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CreditLimit {
            get {
                return this.CreditLimitField;
            }
            set {
                if ((this.CreditLimitField.Equals(value) != true)) {
                    this.CreditLimitField = value;
                    this.RaisePropertyChanged("CreditLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Issuer {
            get {
                return this.IssuerField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuerField, value) != true)) {
                    this.IssuerField = value;
                    this.RaisePropertyChanged("Issuer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ChargeBranch {
            get {
                return this.ChargeBranchField;
            }
            set {
                if ((object.ReferenceEquals(this.ChargeBranchField, value) != true)) {
                    this.ChargeBranchField = value;
                    this.RaisePropertyChanged("ChargeBranch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ChargeLedger {
            get {
                return this.ChargeLedgerField;
            }
            set {
                if ((object.ReferenceEquals(this.ChargeLedgerField, value) != true)) {
                    this.ChargeLedgerField = value;
                    this.RaisePropertyChanged("ChargeLedger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ChargeAccount {
            get {
                return this.ChargeAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.ChargeAccountField, value) != true)) {
                    this.ChargeAccountField = value;
                    this.RaisePropertyChanged("ChargeAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<decimal> MinPaymentAmount {
            get {
                return this.MinPaymentAmountField;
            }
            set {
                if ((this.MinPaymentAmountField.Equals(value) != true)) {
                    this.MinPaymentAmountField = value;
                    this.RaisePropertyChanged("MinPaymentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime AuthorizationLimitValidTo {
            get {
                return this.AuthorizationLimitValidToField;
            }
            set {
                if ((this.AuthorizationLimitValidToField.Equals(value) != true)) {
                    this.AuthorizationLimitValidToField = value;
                    this.RaisePropertyChanged("AuthorizationLimitValidTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<decimal> AugmentedAuthorizationLimit {
            get {
                return this.AugmentedAuthorizationLimitField;
            }
            set {
                if ((this.AugmentedAuthorizationLimitField.Equals(value) != true)) {
                    this.AugmentedAuthorizationLimitField = value;
                    this.RaisePropertyChanged("AugmentedAuthorizationLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime AugmentedAuthorizationLimitExpiration {
            get {
                return this.AugmentedAuthorizationLimitExpirationField;
            }
            set {
                if ((this.AugmentedAuthorizationLimitExpirationField.Equals(value) != true)) {
                    this.AugmentedAuthorizationLimitExpirationField = value;
                    this.RaisePropertyChanged("AugmentedAuthorizationLimitExpiration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.Amount ForeignAuthorizationLimit {
            get {
                return this.ForeignAuthorizationLimitField;
            }
            set {
                if ((object.ReferenceEquals(this.ForeignAuthorizationLimitField, value) != true)) {
                    this.ForeignAuthorizationLimitField = value;
                    this.RaisePropertyChanged("ForeignAuthorizationLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.Amount AugmentedDomesticAuthorizationLimit {
            get {
                return this.AugmentedDomesticAuthorizationLimitField;
            }
            set {
                if ((object.ReferenceEquals(this.AugmentedDomesticAuthorizationLimitField, value) != true)) {
                    this.AugmentedDomesticAuthorizationLimitField = value;
                    this.RaisePropertyChanged("AugmentedDomesticAuthorizationLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.DateTime AugmentedDomesticAuthorizationLimitExpiration {
            get {
                return this.AugmentedDomesticAuthorizationLimitExpirationField;
            }
            set {
                if ((this.AugmentedDomesticAuthorizationLimitExpirationField.Equals(value) != true)) {
                    this.AugmentedDomesticAuthorizationLimitExpirationField = value;
                    this.RaisePropertyChanged("AugmentedDomesticAuthorizationLimitExpiration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.Amount AugmentedForeignAuthorizationLimit {
            get {
                return this.AugmentedForeignAuthorizationLimitField;
            }
            set {
                if ((object.ReferenceEquals(this.AugmentedForeignAuthorizationLimitField, value) != true)) {
                    this.AugmentedForeignAuthorizationLimitField = value;
                    this.RaisePropertyChanged("AugmentedForeignAuthorizationLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.DateTime AugmentedForeignAuthorizationLimitExpiration {
            get {
                return this.AugmentedForeignAuthorizationLimitExpirationField;
            }
            set {
                if ((this.AugmentedForeignAuthorizationLimitExpirationField.Equals(value) != true)) {
                    this.AugmentedForeignAuthorizationLimitExpirationField = value;
                    this.RaisePropertyChanged("AugmentedForeignAuthorizationLimitExpiration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public bool IcelandairLoyaltyClub {
            get {
                return this.IcelandairLoyaltyClubField;
            }
            set {
                if ((this.IcelandairLoyaltyClubField.Equals(value) != true)) {
                    this.IcelandairLoyaltyClubField = value;
                    this.RaisePropertyChanged("IcelandairLoyaltyClub");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public bool PaymentMethod {
            get {
                return this.PaymentMethodField;
            }
            set {
                if ((this.PaymentMethodField.Equals(value) != true)) {
                    this.PaymentMethodField = value;
                    this.RaisePropertyChanged("PaymentMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public System.DateTime PaymentDueDate {
            get {
                return this.PaymentDueDateField;
            }
            set {
                if ((this.PaymentDueDateField.Equals(value) != true)) {
                    this.PaymentDueDateField = value;
                    this.RaisePropertyChanged("PaymentDueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public System.DateTime LastPaymentDate {
            get {
                return this.LastPaymentDateField;
            }
            set {
                if ((this.LastPaymentDateField.Equals(value) != true)) {
                    this.LastPaymentDateField = value;
                    this.RaisePropertyChanged("LastPaymentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public bool DeclineBillingStatement {
            get {
                return this.DeclineBillingStatementField;
            }
            set {
                if ((this.DeclineBillingStatementField.Equals(value) != true)) {
                    this.DeclineBillingStatementField = value;
                    this.RaisePropertyChanged("DeclineBillingStatement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public bool InCollection {
            get {
                return this.InCollectionField;
            }
            set {
                if ((this.InCollectionField.Equals(value) != true)) {
                    this.InCollectionField = value;
                    this.RaisePropertyChanged("InCollection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public System.Nullable<decimal> OlderDebtAmount {
            get {
                return this.OlderDebtAmountField;
            }
            set {
                if ((this.OlderDebtAmountField.Equals(value) != true)) {
                    this.OlderDebtAmountField = value;
                    this.RaisePropertyChanged("OlderDebtAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public System.Nullable<decimal> PenaltyInterestBase {
            get {
                return this.PenaltyInterestBaseField;
            }
            set {
                if ((this.PenaltyInterestBaseField.Equals(value) != true)) {
                    this.PenaltyInterestBaseField = value;
                    this.RaisePropertyChanged("PenaltyInterestBase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public System.Nullable<decimal> LastDueAmount {
            get {
                return this.LastDueAmountField;
            }
            set {
                if ((this.LastDueAmountField.Equals(value) != true)) {
                    this.LastDueAmountField = value;
                    this.RaisePropertyChanged("LastDueAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public int BillingStatementInDefaultNr {
            get {
                return this.BillingStatementInDefaultNrField;
            }
            set {
                if ((this.BillingStatementInDefaultNrField.Equals(value) != true)) {
                    this.BillingStatementInDefaultNrField = value;
                    this.RaisePropertyChanged("BillingStatementInDefaultNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public System.Nullable<decimal> DuePenaltyInterest {
            get {
                return this.DuePenaltyInterestField;
            }
            set {
                if ((this.DuePenaltyInterestField.Equals(value) != true)) {
                    this.DuePenaltyInterestField = value;
                    this.RaisePropertyChanged("DuePenaltyInterest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public System.Nullable<decimal> PenaltyInterestCurrentPeriod {
            get {
                return this.PenaltyInterestCurrentPeriodField;
            }
            set {
                if ((this.PenaltyInterestCurrentPeriodField.Equals(value) != true)) {
                    this.PenaltyInterestCurrentPeriodField = value;
                    this.RaisePropertyChanged("PenaltyInterestCurrentPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public System.Nullable<decimal> TransactionAmountCurrentPeriod {
            get {
                return this.TransactionAmountCurrentPeriodField;
            }
            set {
                if ((this.TransactionAmountCurrentPeriodField.Equals(value) != true)) {
                    this.TransactionAmountCurrentPeriodField = value;
                    this.RaisePropertyChanged("TransactionAmountCurrentPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public System.Nullable<decimal> CardInstallmentLoanRemainingBalance {
            get {
                return this.CardInstallmentLoanRemainingBalanceField;
            }
            set {
                if ((this.CardInstallmentLoanRemainingBalanceField.Equals(value) != true)) {
                    this.CardInstallmentLoanRemainingBalanceField = value;
                    this.RaisePropertyChanged("CardInstallmentLoanRemainingBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=28)]
        public System.Nullable<decimal> CardPaymentDistributionLoanRemainingBalance {
            get {
                return this.CardPaymentDistributionLoanRemainingBalanceField;
            }
            set {
                if ((this.CardPaymentDistributionLoanRemainingBalanceField.Equals(value) != true)) {
                    this.CardPaymentDistributionLoanRemainingBalanceField = value;
                    this.RaisePropertyChanged("CardPaymentDistributionLoanRemainingBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        public System.Nullable<decimal> LightCardInstallmentLoanRemainingBalance {
            get {
                return this.LightCardInstallmentLoanRemainingBalanceField;
            }
            set {
                if ((this.LightCardInstallmentLoanRemainingBalanceField.Equals(value) != true)) {
                    this.LightCardInstallmentLoanRemainingBalanceField = value;
                    this.RaisePropertyChanged("LightCardInstallmentLoanRemainingBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=30)]
        public bool IsPrepaid {
            get {
                return this.IsPrepaidField;
            }
            set {
                if ((this.IsPrepaidField.Equals(value) != true)) {
                    this.IsPrepaidField = value;
                    this.RaisePropertyChanged("IsPrepaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=31)]
        public bool PrePaidBalance {
            get {
                return this.PrePaidBalanceField;
            }
            set {
                if ((this.PrePaidBalanceField.Equals(value) != true)) {
                    this.PrePaidBalanceField = value;
                    this.RaisePropertyChanged("PrePaidBalance");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankErrorFault", Namespace="http://schemas.b2b.is/CreditCards/2013/09/01/Faults")]
    [System.SerializableAttribute()]
    public partial class BankErrorFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneralErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneralErrorTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BanksErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BanksErrorTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneralSourceTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneralSourceCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralErrorCode {
            get {
                return this.GeneralErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneralErrorCodeField, value) != true)) {
                    this.GeneralErrorCodeField = value;
                    this.RaisePropertyChanged("GeneralErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralErrorText {
            get {
                return this.GeneralErrorTextField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneralErrorTextField, value) != true)) {
                    this.GeneralErrorTextField = value;
                    this.RaisePropertyChanged("GeneralErrorText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string BanksErrorCode {
            get {
                return this.BanksErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BanksErrorCodeField, value) != true)) {
                    this.BanksErrorCodeField = value;
                    this.RaisePropertyChanged("BanksErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string BanksErrorText {
            get {
                return this.BanksErrorTextField;
            }
            set {
                if ((object.ReferenceEquals(this.BanksErrorTextField, value) != true)) {
                    this.BanksErrorTextField = value;
                    this.RaisePropertyChanged("BanksErrorText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string GeneralSourceText {
            get {
                return this.GeneralSourceTextField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneralSourceTextField, value) != true)) {
                    this.GeneralSourceTextField = value;
                    this.RaisePropertyChanged("GeneralSourceText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string GeneralSourceCode {
            get {
                return this.GeneralSourceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneralSourceCodeField, value) != true)) {
                    this.GeneralSourceCodeField = value;
                    this.RaisePropertyChanged("GeneralSourceCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCardTransactionResult", Namespace="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardTypes")]
    [System.SerializableAttribute()]
    public partial class CreditCardTransactionResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.Collection<IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.CreditCardTransaction> TransactionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.Paging PagingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.Collection<IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.CreditCardTransaction> Transactions {
            get {
                return this.TransactionsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionsField, value) != true)) {
                    this.TransactionsField = value;
                    this.RaisePropertyChanged("Transactions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.Paging Paging {
            get {
                return this.PagingField;
            }
            set {
                if ((object.ReferenceEquals(this.PagingField, value) != true)) {
                    this.PagingField = value;
                    this.RaisePropertyChanged("Paging");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paging", Namespace="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardTypes")]
    [System.SerializableAttribute()]
    public partial class Paging : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCardTransaction", Namespace="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardTypes")]
    [System.SerializableAttribute()]
    public partial class CreditCardTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CardIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransactionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.Amount ForeignAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.Amount AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorizationNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IcelandairLoyaltyClubTransactionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssuerBranchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantCountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEcardTransactionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CardId {
            get {
                return this.CardIdField;
            }
            set {
                if ((this.CardIdField.Equals(value) != true)) {
                    this.CardIdField = value;
                    this.RaisePropertyChanged("CardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransactionDate {
            get {
                return this.TransactionDateField;
            }
            set {
                if ((this.TransactionDateField.Equals(value) != true)) {
                    this.TransactionDateField = value;
                    this.RaisePropertyChanged("TransactionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.Amount ForeignAmount {
            get {
                return this.ForeignAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.ForeignAmountField, value) != true)) {
                    this.ForeignAmountField = value;
                    this.RaisePropertyChanged("ForeignAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.Amount Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string CurrencyCode {
            get {
                return this.CurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyCodeField, value) != true)) {
                    this.CurrencyCodeField = value;
                    this.RaisePropertyChanged("CurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DueDateField, value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string TransactionKey {
            get {
                return this.TransactionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionKeyField, value) != true)) {
                    this.TransactionKeyField = value;
                    this.RaisePropertyChanged("TransactionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string AuthorizationNumber {
            get {
                return this.AuthorizationNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorizationNumberField, value) != true)) {
                    this.AuthorizationNumberField = value;
                    this.RaisePropertyChanged("AuthorizationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int IcelandairLoyaltyClubTransaction {
            get {
                return this.IcelandairLoyaltyClubTransactionField;
            }
            set {
                if ((this.IcelandairLoyaltyClubTransactionField.Equals(value) != true)) {
                    this.IcelandairLoyaltyClubTransactionField = value;
                    this.RaisePropertyChanged("IcelandairLoyaltyClubTransaction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string IssuerBranch {
            get {
                return this.IssuerBranchField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuerBranchField, value) != true)) {
                    this.IssuerBranchField = value;
                    this.RaisePropertyChanged("IssuerBranch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string MerchantName {
            get {
                return this.MerchantNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantNameField, value) != true)) {
                    this.MerchantNameField = value;
                    this.RaisePropertyChanged("MerchantName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string MerchantCity {
            get {
                return this.MerchantCityField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantCityField, value) != true)) {
                    this.MerchantCityField = value;
                    this.RaisePropertyChanged("MerchantCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string MerchantCountryCode {
            get {
                return this.MerchantCountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantCountryCodeField, value) != true)) {
                    this.MerchantCountryCodeField = value;
                    this.RaisePropertyChanged("MerchantCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public bool IsEcardTransaction {
            get {
                return this.IsEcardTransactionField;
            }
            set {
                if ((this.IsEcardTransactionField.Equals(value) != true)) {
                    this.IsEcardTransactionField = value;
                    this.RaisePropertyChanged("IsEcardTransaction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardService", ConfigurationName="CreditCard20130901Proxy.ICreditCardService")]
    public interface ICreditCardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardService/ICreditCardService" +
            "/GetCreditCards", ReplyAction="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardService/ICreditCardService" +
            "/GetCreditCardsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.BankErrorFault), Action="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardService/ICreditCardService" +
            "/GetCreditCardsBankErrorFaultFault", Name="BankErrorFault", Namespace="http://schemas.b2b.is/CreditCards/2013/09/01/Faults")]
        System.Collections.ObjectModel.Collection<IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.CreditCard> GetCreditCards();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardService/ICreditCardService" +
            "/GetCreditCard", ReplyAction="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardService/ICreditCardService" +
            "/GetCreditCardResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.BankErrorFault), Action="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardService/ICreditCardService" +
            "/GetCreditCardBankErrorFaultFault", Name="BankErrorFault", Namespace="http://schemas.b2b.is/CreditCards/2013/09/01/Faults")]
        IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.CreditCardDetails GetCreditCard(long cardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardService/ICreditCardService" +
            "/GetCreditCardTransactionsByDate", ReplyAction="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardService/ICreditCardService" +
            "/GetCreditCardTransactionsByDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.BankErrorFault), Action="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardService/ICreditCardService" +
            "/GetCreditCardTransactionsByDateBankErrorFaultFault", Name="BankErrorFault", Namespace="http://schemas.b2b.is/CreditCards/2013/09/01/Faults")]
        IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.CreditCardTransactionResult GetCreditCardTransactionsByDate(long cardId, System.DateTime dateFrom, System.DateTime dateTo, int pageNumber, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardService/ICreditCardService" +
            "/GetCreditCardTransactionsByDueDate", ReplyAction="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardService/ICreditCardService" +
            "/GetCreditCardTransactionsByDueDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.BankErrorFault), Action="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardService/ICreditCardService" +
            "/GetCreditCardTransactionsByDueDateBankErrorFaultFault", Name="BankErrorFault", Namespace="http://schemas.b2b.is/CreditCards/2013/09/01/Faults")]
        IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.CreditCardTransactionResult GetCreditCardTransactionsByDueDate(long cardId, string dueDate, int pageNumber, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardService/ICreditCardService" +
            "/GetCreditCardTransactions", ReplyAction="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardService/ICreditCardService" +
            "/GetCreditCardTransactionsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.BankErrorFault), Action="http://schemas.b2b.is/CreditCards/2013/09/01/CreditCardService/ICreditCardService" +
            "/GetCreditCardTransactionsBankErrorFaultFault", Name="BankErrorFault", Namespace="http://schemas.b2b.is/CreditCards/2013/09/01/Faults")]
        IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.CreditCardTransactionResult GetCreditCardTransactions(long cardId, int pageNumber, int pageSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreditCardServiceChannel : IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.ICreditCardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditCardServiceClient : System.ServiceModel.ClientBase<IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.ICreditCardService>, IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.ICreditCardService {
        
        public CreditCardServiceClient() {
        }
        
        public CreditCardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditCardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditCardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditCardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.ObjectModel.Collection<IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.CreditCard> GetCreditCards() {
            return base.Channel.GetCreditCards();
        }
        
        public IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.CreditCardDetails GetCreditCard(long cardId) {
            return base.Channel.GetCreditCard(cardId);
        }
        
        public IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.CreditCardTransactionResult GetCreditCardTransactionsByDate(long cardId, System.DateTime dateFrom, System.DateTime dateTo, int pageNumber, int pageSize) {
            return base.Channel.GetCreditCardTransactionsByDate(cardId, dateFrom, dateTo, pageNumber, pageSize);
        }
        
        public IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.CreditCardTransactionResult GetCreditCardTransactionsByDueDate(long cardId, string dueDate, int pageNumber, int pageSize) {
            return base.Channel.GetCreditCardTransactionsByDueDate(cardId, dueDate, pageNumber, pageSize);
        }
        
        public IsIT.B2B.CreditCardServiceTest.CreditCard20130901Proxy.CreditCardTransactionResult GetCreditCardTransactions(long cardId, int pageNumber, int pageSize) {
            return base.Channel.GetCreditCardTransactions(cardId, pageNumber, pageSize);
        }
    }
}
