//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IsIT.B2B.DoPaymentTest.PaymentsService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IcelandicOnlineBankingPaymentsSoap", Namespace="http://IcelandicOnlineBanking/2005/12/01/Payments")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Receipt))]
    public partial class IcelandicOnlineBankingPaymentsService : Microsoft.Web.Services3.WebServicesClientProtocol
    {
        
        private System.Threading.SendOrPostCallback DoPaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback DoPaymentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPaymentResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPaymentsResultOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IcelandicOnlineBankingPaymentsService() {
            this.Url = global::IsIT.B2B.DoPaymentTest.Properties.Settings.Default.IsIT_B2B_DoPaymentTest_PaymentsService_IcelandicOnlineBankingPaymentsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DoPaymentCompletedEventHandler DoPaymentCompleted;
        
        /// <remarks/>
        public event DoPaymentsCompletedEventHandler DoPaymentsCompleted;
        
        /// <remarks/>
        public event GetPaymentResultCompletedEventHandler GetPaymentResultCompleted;
        
        /// <remarks/>
        public event GetPaymentsResultCompletedEventHandler GetPaymentsResultCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://IcelandicOnlineBanking/2005/12/01/DoPayment", RequestNamespace="http://IcelandicOnlineBanking/2005/12/01/Payments", ResponseNamespace="http://IcelandicOnlineBanking/2005/12/01/Payments", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("paymentsResult")]
        public PaymentsResult DoPayment(Payment payment) {
            object[] results = this.Invoke("DoPayment", new object[] {
                        payment});
            return ((PaymentsResult)(results[0]));
        }
        
        /// <remarks/>
        public void DoPaymentAsync(Payment payment) {
            this.DoPaymentAsync(payment, null);
        }
        
        /// <remarks/>
        public void DoPaymentAsync(Payment payment, object userState) {
            if ((this.DoPaymentOperationCompleted == null)) {
                this.DoPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoPaymentOperationCompleted);
            }
            this.InvokeAsync("DoPayment", new object[] {
                        payment}, this.DoPaymentOperationCompleted, userState);
        }
        
        private void OnDoPaymentOperationCompleted(object arg) {
            if ((this.DoPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoPaymentCompleted(this, new DoPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://IcelandicOnlineBanking/2005/12/01/DoPayments", RequestNamespace="http://IcelandicOnlineBanking/2005/12/01/Payments", ResponseNamespace="http://IcelandicOnlineBanking/2005/12/01/Payments", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("paymentsID")]
        public string DoPayments(Payments payments) {
            object[] results = this.Invoke("DoPayments", new object[] {
                        payments});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DoPaymentsAsync(Payments payments) {
            this.DoPaymentsAsync(payments, null);
        }
        
        /// <remarks/>
        public void DoPaymentsAsync(Payments payments, object userState) {
            if ((this.DoPaymentsOperationCompleted == null)) {
                this.DoPaymentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoPaymentsOperationCompleted);
            }
            this.InvokeAsync("DoPayments", new object[] {
                        payments}, this.DoPaymentsOperationCompleted, userState);
        }
        
        private void OnDoPaymentsOperationCompleted(object arg) {
            if ((this.DoPaymentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoPaymentsCompleted(this, new DoPaymentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://IcelandicOnlineBanking/2005/12/01/GetPaymentResult", RequestNamespace="http://IcelandicOnlineBanking/2005/12/01/Payments", ResponseNamespace="http://IcelandicOnlineBanking/2005/12/01/Payments", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("paymentsResult")]
        public PaymentsResult GetPaymentResult(string paymentID) {
            object[] results = this.Invoke("GetPaymentResult", new object[] {
                        paymentID});
            return ((PaymentsResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetPaymentResultAsync(string paymentID) {
            this.GetPaymentResultAsync(paymentID, null);
        }
        
        /// <remarks/>
        public void GetPaymentResultAsync(string paymentID, object userState) {
            if ((this.GetPaymentResultOperationCompleted == null)) {
                this.GetPaymentResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPaymentResultOperationCompleted);
            }
            this.InvokeAsync("GetPaymentResult", new object[] {
                        paymentID}, this.GetPaymentResultOperationCompleted, userState);
        }
        
        private void OnGetPaymentResultOperationCompleted(object arg) {
            if ((this.GetPaymentResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPaymentResultCompleted(this, new GetPaymentResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://IcelandicOnlineBanking/2005/12/01/GetPaymentsResult", RequestNamespace="http://IcelandicOnlineBanking/2005/12/01/Payments", ResponseNamespace="http://IcelandicOnlineBanking/2005/12/01/Payments", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("paymentsResult")]
        public PaymentsResult GetPaymentsResult(string paymentID, PaymentsStatus filter) {
            object[] results = this.Invoke("GetPaymentsResult", new object[] {
                        paymentID,
                        filter});
            return ((PaymentsResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetPaymentsResultAsync(string paymentID, PaymentsStatus filter) {
            this.GetPaymentsResultAsync(paymentID, filter, null);
        }
        
        /// <remarks/>
        public void GetPaymentsResultAsync(string paymentID, PaymentsStatus filter, object userState) {
            if ((this.GetPaymentsResultOperationCompleted == null)) {
                this.GetPaymentsResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPaymentsResultOperationCompleted);
            }
            this.InvokeAsync("GetPaymentsResult", new object[] {
                        paymentID,
                        filter}, this.GetPaymentsResultOperationCompleted, userState);
        }
        
        private void OnGetPaymentsResultOperationCompleted(object arg) {
            if ((this.GetPaymentsResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPaymentsResultCompleted(this, new GetPaymentsResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public partial class Payment {
        
        private PaymentOut outField;
        
        private PaymentIn inField;
        
        private System.DateTime dateOfForwardPaymentField;
        
        /// <remarks/>
        public PaymentOut Out {
            get {
                return this.outField;
            }
            set {
                this.outField = value;
            }
        }
        
        /// <remarks/>
        public PaymentIn In {
            get {
                return this.inField;
            }
            set {
                this.inField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateOfForwardPayment {
            get {
                return this.dateOfForwardPaymentField;
            }
            set {
                this.dateOfForwardPaymentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public partial class PaymentOut {
        
        private string accountField;
        
        private string accountOwnerIDField;
        
        private string categoryCodeField;
        
        private string referenceField;
        
        private string billNumberField;
        
        private Communication receiptField;
        
        /// <remarks/>
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        public string AccountOwnerID {
            get {
                return this.accountOwnerIDField;
            }
            set {
                this.accountOwnerIDField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public string BillNumber {
            get {
                return this.billNumberField;
            }
            set {
                this.billNumberField = value;
            }
        }
        
        /// <remarks/>
        public Communication Receipt {
            get {
                return this.receiptField;
            }
            set {
                this.receiptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public partial class Communication {
        
        private CommunicationPostalMail postalMailField;
        
        private CommunicationEMail[] eMailField;
        
        private CommunicationSMS[] sMSField;
        
        /// <remarks/>
        public CommunicationPostalMail PostalMail {
            get {
                return this.postalMailField;
            }
            set {
                this.postalMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EMail")]
        public CommunicationEMail[] EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SMS")]
        public CommunicationSMS[] SMS {
            get {
                return this.sMSField;
            }
            set {
                this.sMSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public partial class CommunicationPostalMail : Receipt {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReceiverAddress", typeof(Address))]
        [System.Xml.Serialization.XmlElementAttribute("UsePersonID", typeof(bool))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/CommonTypes")]
    public partial class Address {
        
        private string nameField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string postCodeNumberField;
        
        private string cityField;
        
        private string regionField;
        
        private string countryField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        public string PostCodeNumber {
            get {
                return this.postCodeNumberField;
            }
            set {
                this.postCodeNumberField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public partial class Payments {
        
        private PaymentOut outField;
        
        private PaymentIn[] inField;
        
        private System.DateTime dateOfForwardPaymentField;
        
        private string nameOfBatchField;
        
        private bool rollbackOnErrorField;
        
        private bool isOneToManyField;
        
        /// <remarks/>
        public PaymentOut Out {
            get {
                return this.outField;
            }
            set {
                this.outField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("In")]
        public PaymentIn[] In {
            get {
                return this.inField;
            }
            set {
                this.inField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateOfForwardPayment {
            get {
                return this.dateOfForwardPaymentField;
            }
            set {
                this.dateOfForwardPaymentField = value;
            }
        }
        
        /// <remarks/>
        public string NameOfBatch {
            get {
                return this.nameOfBatchField;
            }
            set {
                this.nameOfBatchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool RollbackOnError {
            get {
                return this.rollbackOnErrorField;
            }
            set {
                this.rollbackOnErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsOneToMany {
            get {
                return this.isOneToManyField;
            }
            set {
                this.isOneToManyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public partial class PaymentIn {
        
        private object itemField;
        
        private decimal amountField;
        
        private Communication receiptField;
        
        private string descriptionField;
        
        private string bookingIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ABGiro", typeof(ABGiro))]
        [System.Xml.Serialization.XmlElementAttribute("CGiro", typeof(CGiro))]
        [System.Xml.Serialization.XmlElementAttribute("PaymentSlip", typeof(PaymentSlip))]
        [System.Xml.Serialization.XmlElementAttribute("Transfer", typeof(Transfer))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public Communication Receipt {
            get {
                return this.receiptField;
            }
            set {
                this.receiptField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string BookingID {
            get {
                return this.bookingIDField;
            }
            set {
                this.bookingIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public partial class ABGiro {
        
        private string accountField;
        
        private string referenceField;
        
        private string billNumberField;
        
        private string categoryCodeField;
        
        /// <remarks/>
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public string BillNumber {
            get {
                return this.billNumberField;
            }
            set {
                this.billNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public partial class CGiro {
        
        private string accountField;
        
        private string accountOwnerIDField;
        
        private string billNumberField;
        
        private string categoryCodeField;
        
        /// <remarks/>
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        public string AccountOwnerID {
            get {
                return this.accountOwnerIDField;
            }
            set {
                this.accountOwnerIDField = value;
            }
        }
        
        /// <remarks/>
        public string BillNumber {
            get {
                return this.billNumberField;
            }
            set {
                this.billNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaymentSlipInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public partial class PaymentSlip {
        
        private string accountField;
        
        private string personIDField;
        
        private System.DateTime dueDateField;
        
        private bool isDepositField;
        
        /// <remarks/>
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        public string PersonID {
            get {
                return this.personIDField;
            }
            set {
                this.personIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DueDate {
            get {
                return this.dueDateField;
            }
            set {
                this.dueDateField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDeposit {
            get {
                return this.isDepositField;
            }
            set {
                this.isDepositField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public partial class PaymentSlipInfo : PaymentSlip {
        
        private decimal amountDueField;
        
        private decimal defaultCostsField;
        
        private decimal otherCostsField;
        
        private decimal otherDefaultCostsField;
        
        private decimal defaultInterestField;
        
        private decimal noticeAndPaymentFeeField;
        
        private decimal discountField;
        
        private string categoryCodeField;
        
        /// <remarks/>
        public decimal AmountDue {
            get {
                return this.amountDueField;
            }
            set {
                this.amountDueField = value;
            }
        }
        
        /// <remarks/>
        public decimal DefaultCosts {
            get {
                return this.defaultCostsField;
            }
            set {
                this.defaultCostsField = value;
            }
        }
        
        /// <remarks/>
        public decimal OtherCosts {
            get {
                return this.otherCostsField;
            }
            set {
                this.otherCostsField = value;
            }
        }
        
        /// <remarks/>
        public decimal OtherDefaultCosts {
            get {
                return this.otherDefaultCostsField;
            }
            set {
                this.otherDefaultCostsField = value;
            }
        }
        
        /// <remarks/>
        public decimal DefaultInterest {
            get {
                return this.defaultInterestField;
            }
            set {
                this.defaultInterestField = value;
            }
        }
        
        /// <remarks/>
        public decimal NoticeAndPaymentFee {
            get {
                return this.noticeAndPaymentFeeField;
            }
            set {
                this.noticeAndPaymentFeeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Discount {
            get {
                return this.discountField;
            }
            set {
                this.discountField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public partial class Transfer {
        
        private string accountField;
        
        private string accountOwnerIDField;
        
        private string categoryCodeField;
        
        private string referenceField;
        
        private string billNumberField;
        
        /// <remarks/>
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        public string AccountOwnerID {
            get {
                return this.accountOwnerIDField;
            }
            set {
                this.accountOwnerIDField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public string BillNumber {
            get {
                return this.billNumberField;
            }
            set {
                this.billNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/CommonTypes")]
    public partial class Error {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public partial class PaymentError {
        
        private PaymentIn paymentField;
        
        private Error errorField;
        
        /// <remarks/>
        public PaymentIn Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        public Error Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public partial class PaymentResultDetails {
        
        private object itemField;
        
        private decimal amountField;
        
        private Communication receiptField;
        
        private string descriptionField;
        
        private string bookingIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ABGiro", typeof(ABGiro))]
        [System.Xml.Serialization.XmlElementAttribute("CGiro", typeof(CGiro))]
        [System.Xml.Serialization.XmlElementAttribute("PaymentSlip", typeof(PaymentSlipInfo))]
        [System.Xml.Serialization.XmlElementAttribute("Transfer", typeof(Transfer))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public Communication Receipt {
            get {
                return this.receiptField;
            }
            set {
                this.receiptField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string BookingID {
            get {
                return this.bookingIDField;
            }
            set {
                this.bookingIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public partial class PaymentsResult {
        
        private string idField;
        
        private BatchStatus statusField;
        
        private PaymentResultDetails[] successField;
        
        private PaymentError[] errorsField;
        
        private System.DateTime dateOfPaymentField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public BatchStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Success")]
        public PaymentResultDetails[] Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Errors")]
        public PaymentError[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateOfPayment {
            get {
                return this.dateOfPaymentField;
            }
            set {
                this.dateOfPaymentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public enum BatchStatus {
        
        /// <remarks/>
        InProgress,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        CompletedWithErrors,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        OnHold,
        
        /// <remarks/>
        NotConfirmed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/CommonTypes")]
    public partial class PhoneNumber {
        
        private string countryCodeField;
        
        private string numberField;
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public abstract partial class Receipt {
        
        private string languageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public partial class CommunicationEMail : Receipt {
        
        private string emailAddressField;
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public partial class CommunicationSMS : Receipt {
        
        private PhoneNumber phoneNumberField;
        
        /// <remarks/>
        public PhoneNumber PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes")]
    public enum PaymentsStatus {
        
        /// <remarks/>
        GetStatus,
        
        /// <remarks/>
        GetErrors,
        
        /// <remarks/>
        GetOkay,
        
        /// <remarks/>
        GetAll,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DoPaymentCompletedEventHandler(object sender, DoPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DoPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PaymentsResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PaymentsResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DoPaymentsCompletedEventHandler(object sender, DoPaymentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoPaymentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DoPaymentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetPaymentResultCompletedEventHandler(object sender, GetPaymentResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPaymentResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPaymentResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PaymentsResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PaymentsResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetPaymentsResultCompletedEventHandler(object sender, GetPaymentsResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPaymentsResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPaymentsResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PaymentsResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PaymentsResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591