//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForeignAccountTransactionQuery", Namespace="http://schemas.b2b.is/2015/08/01/ForeignStatementTypes")]
    [System.SerializableAttribute()]
    public partial class ForeignAccountTransactionQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateFrom {
            get {
                return this.DateFromField;
            }
            set {
                if ((this.DateFromField.Equals(value) != true)) {
                    this.DateFromField = value;
                    this.RaisePropertyChanged("DateFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTo {
            get {
                return this.DateToField;
            }
            set {
                if ((this.DateToField.Equals(value) != true)) {
                    this.DateToField = value;
                    this.RaisePropertyChanged("DateTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForeignAccountTransactionsResult", Namespace="http://schemas.b2b.is/2015/08/01/ForeignStatementTypes")]
    [System.SerializableAttribute()]
    public partial class ForeignAccountTransactionsResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccount AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.Collection<IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccountTransaction> TransactionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccount Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.Collection<IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccountTransaction> Transactions {
            get {
                return this.TransactionsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionsField, value) != true)) {
                    this.TransactionsField = value;
                    this.RaisePropertyChanged("Transactions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForeignAccount", Namespace="http://schemas.b2b.is/2015/08/01/ForeignStatementTypes")]
    [System.SerializableAttribute()]
    public partial class ForeignAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerPersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccountDetails DetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountTypeField, value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerName {
            get {
                return this.OwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerNameField, value) != true)) {
                    this.OwnerNameField = value;
                    this.RaisePropertyChanged("OwnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerPersonId {
            get {
                return this.OwnerPersonIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerPersonIdField, value) != true)) {
                    this.OwnerPersonIdField = value;
                    this.RaisePropertyChanged("OwnerPersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccountDetails Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForeignAccountTransaction", Namespace="http://schemas.b2b.is/2015/08/01/ForeignStatementTypes")]
    [System.SerializableAttribute()]
    public partial class ForeignAccountTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelatedReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatementNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SequenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StatementDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OpeningBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ValueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EntryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DebitCreditMarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPaymentReversedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FundsCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ClosingBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InterimBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ClosingAvailableBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ForwardAvailableBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtraDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedTimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNumber {
            get {
                return this.ReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNumberField, value) != true)) {
                    this.ReferenceNumberField = value;
                    this.RaisePropertyChanged("ReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelatedReference {
            get {
                return this.RelatedReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.RelatedReferenceField, value) != true)) {
                    this.RelatedReferenceField = value;
                    this.RaisePropertyChanged("RelatedReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatementNumber {
            get {
                return this.StatementNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StatementNumberField, value) != true)) {
                    this.StatementNumberField = value;
                    this.RaisePropertyChanged("StatementNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string SequenceNumber {
            get {
                return this.SequenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SequenceNumberField, value) != true)) {
                    this.SequenceNumberField = value;
                    this.RaisePropertyChanged("SequenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime StatementDate {
            get {
                return this.StatementDateField;
            }
            set {
                if ((this.StatementDateField.Equals(value) != true)) {
                    this.StatementDateField = value;
                    this.RaisePropertyChanged("StatementDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal OpeningBalance {
            get {
                return this.OpeningBalanceField;
            }
            set {
                if ((this.OpeningBalanceField.Equals(value) != true)) {
                    this.OpeningBalanceField = value;
                    this.RaisePropertyChanged("OpeningBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime ValueDate {
            get {
                return this.ValueDateField;
            }
            set {
                if ((this.ValueDateField.Equals(value) != true)) {
                    this.ValueDateField = value;
                    this.RaisePropertyChanged("ValueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime EntryDate {
            get {
                return this.EntryDateField;
            }
            set {
                if ((this.EntryDateField.Equals(value) != true)) {
                    this.EntryDateField = value;
                    this.RaisePropertyChanged("EntryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string DebitCreditMark {
            get {
                return this.DebitCreditMarkField;
            }
            set {
                if ((object.ReferenceEquals(this.DebitCreditMarkField, value) != true)) {
                    this.DebitCreditMarkField = value;
                    this.RaisePropertyChanged("DebitCreditMark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool IsPaymentReversed {
            get {
                return this.IsPaymentReversedField;
            }
            set {
                if ((this.IsPaymentReversedField.Equals(value) != true)) {
                    this.IsPaymentReversedField = value;
                    this.RaisePropertyChanged("IsPaymentReversed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string FundsCode {
            get {
                return this.FundsCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FundsCodeField, value) != true)) {
                    this.FundsCodeField = value;
                    this.RaisePropertyChanged("FundsCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string TransactionType {
            get {
                return this.TransactionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionTypeField, value) != true)) {
                    this.TransactionTypeField = value;
                    this.RaisePropertyChanged("TransactionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string CustomerReference {
            get {
                return this.CustomerReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerReferenceField, value) != true)) {
                    this.CustomerReferenceField = value;
                    this.RaisePropertyChanged("CustomerReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string BankReference {
            get {
                return this.BankReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.BankReferenceField, value) != true)) {
                    this.BankReferenceField = value;
                    this.RaisePropertyChanged("BankReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public decimal ClosingBalance {
            get {
                return this.ClosingBalanceField;
            }
            set {
                if ((this.ClosingBalanceField.Equals(value) != true)) {
                    this.ClosingBalanceField = value;
                    this.RaisePropertyChanged("ClosingBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public decimal InterimBalance {
            get {
                return this.InterimBalanceField;
            }
            set {
                if ((this.InterimBalanceField.Equals(value) != true)) {
                    this.InterimBalanceField = value;
                    this.RaisePropertyChanged("InterimBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public decimal ClosingAvailableBalance {
            get {
                return this.ClosingAvailableBalanceField;
            }
            set {
                if ((this.ClosingAvailableBalanceField.Equals(value) != true)) {
                    this.ClosingAvailableBalanceField = value;
                    this.RaisePropertyChanged("ClosingAvailableBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public decimal ForwardAvailableBalance {
            get {
                return this.ForwardAvailableBalanceField;
            }
            set {
                if ((this.ForwardAvailableBalanceField.Equals(value) != true)) {
                    this.ForwardAvailableBalanceField = value;
                    this.RaisePropertyChanged("ForwardAvailableBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string ExtraDescription {
            get {
                return this.ExtraDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraDescriptionField, value) != true)) {
                    this.ExtraDescriptionField = value;
                    this.RaisePropertyChanged("ExtraDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public System.DateTime CreatedTimestamp {
            get {
                return this.CreatedTimestampField;
            }
            set {
                if ((this.CreatedTimestampField.Equals(value) != true)) {
                    this.CreatedTimestampField = value;
                    this.RaisePropertyChanged("CreatedTimestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForeignAccountDetails", Namespace="http://schemas.b2b.is/2015/08/01/ForeignStatementTypes")]
    [System.SerializableAttribute()]
    public partial class ForeignAccountDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SwiftNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SwiftNumber {
            get {
                return this.SwiftNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SwiftNumberField, value) != true)) {
                    this.SwiftNumberField = value;
                    this.RaisePropertyChanged("SwiftNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankErrorFault", Namespace="http://schemas.b2b.is/2015/08/01/Faults")]
    [System.SerializableAttribute()]
    public partial class BankErrorFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BanksErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BanksErrorTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneralErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneralErrorTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BanksErrorCode {
            get {
                return this.BanksErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BanksErrorCodeField, value) != true)) {
                    this.BanksErrorCodeField = value;
                    this.RaisePropertyChanged("BanksErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BanksErrorText {
            get {
                return this.BanksErrorTextField;
            }
            set {
                if ((object.ReferenceEquals(this.BanksErrorTextField, value) != true)) {
                    this.BanksErrorTextField = value;
                    this.RaisePropertyChanged("BanksErrorText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralErrorCode {
            get {
                return this.GeneralErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneralErrorCodeField, value) != true)) {
                    this.GeneralErrorCodeField = value;
                    this.RaisePropertyChanged("GeneralErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralErrorText {
            get {
                return this.GeneralErrorTextField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneralErrorTextField, value) != true)) {
                    this.GeneralErrorTextField = value;
                    this.RaisePropertyChanged("GeneralErrorText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForeignAccountStatementQuery", Namespace="http://schemas.b2b.is/2015/08/01/ForeignStatementTypes")]
    [System.SerializableAttribute()]
    public partial class ForeignAccountStatementQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateFrom {
            get {
                return this.DateFromField;
            }
            set {
                if ((this.DateFromField.Equals(value) != true)) {
                    this.DateFromField = value;
                    this.RaisePropertyChanged("DateFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTo {
            get {
                return this.DateToField;
            }
            set {
                if ((this.DateToField.Equals(value) != true)) {
                    this.DateToField = value;
                    this.RaisePropertyChanged("DateTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForeignAccountStatementResult", Namespace="http://schemas.b2b.is/2015/08/01/ForeignStatementTypes")]
    [System.SerializableAttribute()]
    public partial class ForeignAccountStatementResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccount AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.Collection<IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccountStatement> StatementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccount Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.Collection<IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccountStatement> Statements {
            get {
                return this.StatementsField;
            }
            set {
                if ((object.ReferenceEquals(this.StatementsField, value) != true)) {
                    this.StatementsField = value;
                    this.RaisePropertyChanged("Statements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForeignAccountStatement", Namespace="http://schemas.b2b.is/2015/08/01/ForeignStatementTypes")]
    [System.SerializableAttribute()]
    public partial class ForeignAccountStatement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelatedReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatementNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SequenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StatementDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OpeningBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InterimBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatementDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedTimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNumber {
            get {
                return this.ReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNumberField, value) != true)) {
                    this.ReferenceNumberField = value;
                    this.RaisePropertyChanged("ReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelatedReference {
            get {
                return this.RelatedReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.RelatedReferenceField, value) != true)) {
                    this.RelatedReferenceField = value;
                    this.RaisePropertyChanged("RelatedReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatementNumber {
            get {
                return this.StatementNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StatementNumberField, value) != true)) {
                    this.StatementNumberField = value;
                    this.RaisePropertyChanged("StatementNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string SequenceNumber {
            get {
                return this.SequenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SequenceNumberField, value) != true)) {
                    this.SequenceNumberField = value;
                    this.RaisePropertyChanged("SequenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime StatementDate {
            get {
                return this.StatementDateField;
            }
            set {
                if ((this.StatementDateField.Equals(value) != true)) {
                    this.StatementDateField = value;
                    this.RaisePropertyChanged("StatementDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal OpeningBalance {
            get {
                return this.OpeningBalanceField;
            }
            set {
                if ((this.OpeningBalanceField.Equals(value) != true)) {
                    this.OpeningBalanceField = value;
                    this.RaisePropertyChanged("OpeningBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal InterimBalance {
            get {
                return this.InterimBalanceField;
            }
            set {
                if ((this.InterimBalanceField.Equals(value) != true)) {
                    this.InterimBalanceField = value;
                    this.RaisePropertyChanged("InterimBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string StatementData {
            get {
                return this.StatementDataField;
            }
            set {
                if ((object.ReferenceEquals(this.StatementDataField, value) != true)) {
                    this.StatementDataField = value;
                    this.RaisePropertyChanged("StatementData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime CreatedTimestamp {
            get {
                return this.CreatedTimestampField;
            }
            set {
                if ((this.CreatedTimestampField.Equals(value) != true)) {
                    this.CreatedTimestampField = value;
                    this.RaisePropertyChanged("CreatedTimestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForeignAccountsQuery", Namespace="http://schemas.b2b.is/2015/08/01/ForeignStatementTypes")]
    [System.SerializableAttribute()]
    public partial class ForeignAccountsQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForeignAccountsResult", Namespace="http://schemas.b2b.is/2015/08/01/ForeignStatementTypes")]
    [System.SerializableAttribute()]
    public partial class ForeignAccountsResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.ObjectModel.Collection<IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccount> AccountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.Collection<IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccount> Accounts {
            get {
                return this.AccountsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountsField, value) != true)) {
                    this.AccountsField = value;
                    this.RaisePropertyChanged("Accounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.b2b.is/2015/08/01/ForeignStatements", ConfigurationName="ForeignStatementServiceProxy.IForeignStatementService")]
    public interface IForeignStatementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.b2b.is/2015/08/01/ForeignStatements/IForeignStatementService/GetFo" +
            "reignAccountTransactions", ReplyAction="http://schemas.b2b.is/2015/08/01/ForeignStatements/IForeignStatementService/GetFo" +
            "reignAccountTransactionsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.BankErrorFault), Action="http://schemas.b2b.is/2015/08/01/ForeignStatements/IForeignStatementService/GetFo" +
            "reignAccountTransactionsBankErrorFaultFault", Name="BankErrorFault", Namespace="http://schemas.b2b.is/2015/08/01/Faults")]
        IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccountTransactionsResult GetForeignAccountTransactions(IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccountTransactionQuery query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.b2b.is/2015/08/01/ForeignStatements/IForeignStatementService/GetFo" +
            "reignAccountStatements", ReplyAction="http://schemas.b2b.is/2015/08/01/ForeignStatements/IForeignStatementService/GetFo" +
            "reignAccountStatementsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.BankErrorFault), Action="http://schemas.b2b.is/2015/08/01/ForeignStatements/IForeignStatementService/GetFo" +
            "reignAccountStatementsBankErrorFaultFault", Name="BankErrorFault", Namespace="http://schemas.b2b.is/2015/08/01/Faults")]
        IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccountStatementResult GetForeignAccountStatements(IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccountStatementQuery query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.b2b.is/2015/08/01/ForeignStatements/IForeignStatementService/GetFo" +
            "reignAccounts", ReplyAction="http://schemas.b2b.is/2015/08/01/ForeignStatements/IForeignStatementService/GetFo" +
            "reignAccountsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.BankErrorFault), Action="http://schemas.b2b.is/2015/08/01/ForeignStatements/IForeignStatementService/GetFo" +
            "reignAccountsBankErrorFaultFault", Name="BankErrorFault", Namespace="http://schemas.b2b.is/2015/08/01/Faults")]
        IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccountsResult GetForeignAccounts(IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccountsQuery query);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IForeignStatementServiceChannel : IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.IForeignStatementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ForeignStatementServiceClient : System.ServiceModel.ClientBase<IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.IForeignStatementService>, IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.IForeignStatementService {
        
        public ForeignStatementServiceClient() {
        }
        
        public ForeignStatementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ForeignStatementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForeignStatementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForeignStatementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccountTransactionsResult GetForeignAccountTransactions(IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccountTransactionQuery query) {
            return base.Channel.GetForeignAccountTransactions(query);
        }
        
        public IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccountStatementResult GetForeignAccountStatements(IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccountStatementQuery query) {
            return base.Channel.GetForeignAccountStatements(query);
        }
        
        public IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccountsResult GetForeignAccounts(IsIT.B2B.ForeignStatementServiceTest.ForeignStatementServiceProxy.ForeignAccountsQuery query) {
            return base.Channel.GetForeignAccounts(query);
        }
    }
}
